### ISSUE TITLE
업데이트된 버전을 다시 받았습니다만 말씀드린 문제가 그대로입니다.

### ISSUE THREAD

**Issue by Foxchandaisuki** [HyunjaeLee/ridi-drm#6]
만화책이 아니라 IT 서적이고, 업데이트된 버전을 다시 받았습니다만 해당 문제는 해결이 안 된 상태입니다.

**Comment by HyunjaeLee** [comment]
제 기준으로는 pdf, epub, zip 중 zip만 갑자기 안돼서 수정했는데 상황이 다른가 보네요. pdf, epub, zip 중 어떤 형태의 책인지 알려주시고 스크린 샷도 첨부해주세요.

**Comment by Yeonjunhyuk** [comment]
안녕하세요 올려주신거 사용해봤는데요 [ridi-drm-win32-x64-0.1.3.zip] 이 파일 받아서 압축 풀고 ridi-drm 실행해서 로긴한 후에 작품 다운로드했더니 다운이 중간에 멈춥니다 이펍파일이구요 제가 초보라서; 사용방법이 잘못된건지 여쭙고싶어서 코맨트 답니다.. 혹시 같이 있던 파일들 다 받아야 하는건가요? 아니면 실행순서가 잘못된건가요?

**Comment by Foxchandaisuki** [comment]
![bandicam 2024-04-29 22-17-37-042](https://github.com/HyunjaeLee/ridi-drm/assets/118077852/03eb0636-63a3-44b7-88b2-fb9dc3edc48c)

PDF 파일입니다. 이 상태에서 아무리 기다려도 파잃이 안 받아집니다.

**Comment by HyunjaeLee** [comment]
리눅스 환경에서는 잘 작동하기에 윈도우에 한정된 문제인가 하여 Windows 11 PC에서도 실행을 해 보았지만 pdf, epub, zip 모두 정상적으로 받아져서 오류를 재현할 수 없었습니다.
내부적으로 파일 다운로드를 위해 사용하는 electron-dl 라이브러리와 관련된 이슈일 수도 있겠다는 생각이 들지만, 오류 재현이 안되기에 지금 정보만으로는 버그를 고치기 어려울 것 같습니다.
그래서 로그 기능을 추가해서 v0.1.4를 배포했는데 해당 버전으로 실행해 보시고 로그 파일을 보내주시면 도움이 될 것 같습니다.
윈도우에서 로그 파일은 `C:\Users\{윈도우 계정명}\AppData\Roaming\ridi-drm\logs`에 저장됩니다.

**Comment by SunnyGraffic** [comment]
안녕하세요. ridi-drm을 실행 시 나오는
Authorization
Usename / Password에 리디북x 로그인을 하면 되는 걸까요?
'장기 휴면 계정은 개인정보보호법에 따라 서비스를 이용할 수 없습니다. 회원가입 후 이용해주세요.'라는 안내문구가 뜹니다.

**Comment by Yeonjunhyuk** [comment]
다운받은 파일은 어디에 저장되나요?

**Comment by Foxchandaisuki** [comment]
[main.log](https://github.com/HyunjaeLee/ridi-drm/files/15170929/main.log)

로그 파일 열어보니까 딱 한 줄밖에 안 뜨는데...이거 문제 분석 가능할까요..?

**Comment by HyunjaeLee** [comment]
[v0.1.5](https://github.com/HyunjaeLee/ridi-drm/releases/tag/v0.1.5)

@Yeonjunhyuk 
로그를 보면 다운로드가 되다가 실패하는 것을 볼 수 있는데, 지금으로서는 electron-dl 라이브러리의 문제라고 생각이 됩니다. 그래서 electron-dl을 사용하지 않고 axios와 stream을 사용하도록 수정했습니다. 정말 electron-dl의 문제였는지는 직접 실행을 해 보셔야 알 것 같습니다.
질문에 답을 드리자면, 임시 파일은 로그에서 확인할 수 있는 tempDir에 저장되고 결과물은 Documents\ridi-drm에 저장됩니다. 지금 버전은 GUI에 신경을 쓰지 않았기 때문에 메뉴는 모두 기본값인 상태입니다. 목록으로 나가려면 다운로드가 완료되고 페이지 하단에 있는 DONE을 눌러야 하는데 실패하면 버튼이 뜨지 않으므로, 다운로드가 실패했을 때 뒤로 갈 수 있는 방법은 없습니다. GUI는 추후에 개선할 예정입니다.

@Foxchandaisuki 
다운로드 단계까지도 가지 못하고 함수가 종료된 것으로 보아 폴더 생성 과정에서 문제(권한 문제 등)가 발생한 것이 유력해 보입니다. 다른 가능성으로는 api 호출 과정에서의 문제인데, 로그인과 책 불러오기는 정상적으로 수행된 것으로 보아 가능성은 적어 보입니다. 다만 다운로드 단계에서의 문제로 생각하고 다운로드 준비 단계의 로깅은 제대로 처리해놓지 않았는데, 해당 부분에서 오류가 발생하면 로그를 찍도록 수정했으니 다시 실행해보시고 로그 보내주시면 좋겠습니다.

**Comment by Foxchandaisuki** [comment]
[main.log](https://github.com/HyunjaeLee/ridi-drm/files/15174893/main.log)

> [2024-05-01 16:26:48.283] [error] Error: ENOENT: no such file or directory, mkdir 'C:\Users\(윈도우 계정명)\Documents\ridi-drm'
>   at mkdirSync (node:fs:1379:3)

여전히 다운로드도 안 되는 상태에서 로그 파일을 열어보니 이런 로그가 있길래 수동으로 저 위치에 폴더를 만들어줬습니다. 그랬더니 다운하고 복호화를 했다고 나오는데...정작 파일은 온데간데 없네요.

1. 폴더 생성이 자동으로 안 됨
2. 만들어 준 폴더에 만들어져있어야 하는 파일이 있어야하는데 없음

이 두 가지가 문제인 것 같습니다. 그리고 만들어 준 폴더가 다운로드를 할 때마다 자꾸 읽기 전용으로 바뀌던데 혹시 이거랑 관련이 있을까요?

**Comment by HyunjaeLee** [comment]
Documents 폴더에 쓰기 권한이 없어서 문제가 발생하는 것 같습니다. 프로그램을 유저 권한으로 실행해도 읽기/쓰기가 가능한 폴더로 알고 있는데 이상하네요. 관리자 권한으로 실행해 보시겠어요?

**Comment by Foxchandaisuki** [comment]
처음부터 쭉 관리자 권한으로 실행해왔는데 이런 상태입니다...ㅠㅠ

2024년 5월 1일 (수) 오후 5:06, Hyunjae Lee ***@***.***>님이 작성:

**Comment by HyunjaeLee** [comment]
[v0.1.6](https://github.com/HyunjaeLee/ridi-drm/releases/tag/v0.1.6)
다운로드 경로를 변경 가능하게 하고, 기본 다운로드 경로를 Documents\ridi-drm에서 Downloads로 수정했습니다.
임시 폴더(AppData)에 쓰기가 잘 되는 것을 봐서는 Document 폴더의 권한 이슈가 맞는 것 같은데, Downloads 폴더 또는 다른 폴더를 경로로 설정했을 때 정상적으로 동작하는지 확인해주세요.

**Comment by Yeonjunhyuk** [comment]
선생님 작동 잘 됩니다!
너무 너무 감사합니다!!
마지막으로 하나 여쭤보고 싶은 게 있는데
여기서 추출한 파일에 제 아이디나 고유번호 같은 정보가 포함 되어있을까요?

**Comment by Foxchandaisuki** [comment]
[main.log](https://github.com/HyunjaeLee/ridi-drm/files/15182725/main.log)
이제 파일 다운은 됩니다. 다운로드 폴더에 파일 생성도 됐는데 파일을 열려고 하면 Adobe Digital Editions에서 이 항목에서 오류가 발생했습니다 이러면서 파일이 안 열립니다.

**Comment by Foxchandaisuki** [comment]
다운받은 PDF 파일은 정상적으로 열리는데, EPUB 파일만 안 열리네요...

**Comment by HyunjaeLee** [comment]
어도비 말고 다른 프로그램으로 열어도 오류가 발생하나요?
+ [웹 뷰어](https://epubreader.net/)
+ 리디 PC 뷰어

**Comment by Foxchandaisuki** [comment]
Freda로는 잘 열리네요...어도비가 문제였군요. 이제 잘 됩니다. 흑흑 그동안 고생해주셔서 감사합니다 ㅠㅠ

2024년 5월 2일 (목) 오후 12:14, Hyunjae Lee ***@***.***>님이 작성:
