### ISSUE TITLE
[Solved] I can't download this book

### ISSUE THREAD

**Issue by uksask** [HyunjaeLee/ridi-drm#7]
Thanks for your work!
When I tried to download 극락가(1), it always paused when __ridi__182.jpg was decrypted.
How can I fix this problem?

**Comment by uksask** [comment]
[main.log](https://github.com/HyunjaeLee/ridi-drm/files/15307004/main.log)

**Comment by uksask** [comment]
I don't know why…
But when I set the download path to C:/(maybe because of the same disk with nodejs? ) , the problem was solved.
Thanks for your work again^ ^

**Comment by HyunjaeLee** [comment]
It is fixed in [v0.1.8](https://github.com/HyunjaeLee/ridi-drm/releases/tag/v0.1.8).
